apiVersion: batch/v1
kind: Job
metadata:
  name: feeder
  namespace: am
spec:
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
      - name: feeder
        image: index.docker.io/mateuszdyminski/feeder:latest
        resources:
            requests:
              memory: 100Mi
              cpu: 200m
      restartPolicy: Never
  backoffLimit: 4