apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
  namespace: am
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: indexer
        serviceName: indexer
    spec:
      containers:
      - name: indexer
        image: index.docker.io/mateuszdyminski/indexer:latest
        resources:
            requests:
              memory: 100Mi
              cpu: 200m