---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: am
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: am
spec:
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: web
        serviceName: web
    spec:
      containers:
      - name: web
        image: index.docker.io/mateuszdyminski/am-web:latest
        ports:
          - containerPort: 8080
        resources:
            requests:
              memory: 100Mi
              cpu: 200m