Brokers = [ "kafka-cluster-kafka-bootstrap.kafka:9092" ]
Topic = "users"

SourceDataType = "csv"

DbString = "root:password@tcp(mysql:3306)/am"
CsvPath = "/feeder/data/100-users.csv"
PushgatewayAddress = "prometheus-pushgateway.monitoring:9091" 
