zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  build: .
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    KAFKA_CREATE_TOPICS: "time-series:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
rethinkdb:
  image: rethinkdb
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"