zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
    - "22"
kafka:
  build: .
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 172.17.42.1
    KAFKA_CREATE_TOPICS: "time-series:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links:
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
    - cassandra:cass
    - elasticsearch:es
ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
cassandra:
  image: mateuszdyminski/cassandra:3
  ports:
    - "9160:9160"
    - "9042:9042"
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
