zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  build: .
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    KAFKA_CREATE_TOPICS: "time-series:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
cassandra:
  image: mateuszdyminski/cassandra:3
  ports:
    - "9160:9160"
    - "9042:9042"
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
# etcd:
#   image: quay.io/coreos/etcd-git
#   environment: 
#     ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
#     ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380,http://0.0.0.0:7001"
#     ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
#   ports:
#     - "2379:2379"
#     - "2380:2380"
