Brokers = [ "kafka-cluster-kafka-bootstrap.kafka:9092" ]
Topic = "users"
ReadFromOldest = false
HTTPPort = 8080

Elastics = [ "https://elastic-cluster-es-http.elastic:9200" ]
ElasticUser = "elastic"
ElasticPassword = "password"